
'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useEffect, useState } from 'react';
import { type Post } from './page';
import { useToast } from '@/hooks/use-toast';
import { generateHashtags } from '@/ai/flows/generate-hashtags';
import { Loader2, Wand2 } from 'lucide-react';

type EditPostDialogProps = {
  post: Post | null;
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (updatedPost: Post) => void;
};

export function EditPostDialog({ post, isOpen, onOpenChange, onSave }: EditPostDialogProps) {
  const [caption, setCaption] = useState('');
  const [hashtags, setHashtags] = useState('');
  const [isGeneratingHashtags, setIsGeneratingHashtags] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    if (post) {
      setCaption(post.caption_en);
      setHashtags(post.hashtags.join('\n'));
    }
  }, [post]);

  const handleSave = () => {
    if (post) {
      const updatedPost = {
        ...post,
        caption_en: caption,
        // Also update caption_tr if needed, maybe regenerate it
        caption_tr: caption, // for now just copy
        hashtags: hashtags.split('\n').filter(h => h.trim() !== ''),
      };
      onSave(updatedPost);
      onOpenChange(false);
    }
  };

  const handleRegenerateHashtags = async () => {
    if (!post) return;
    setIsGeneratingHashtags(true);
    try {
      const result = await generateHashtags({
        caption: caption,
        product: post.title, // Assuming title is the product
        // In a real app, city would come from brand settings
        city: 'Istanbul',
      });
      setHashtags(result.hashtags.join('\n'));
      toast({
        title: 'Hashtags Regenerated',
        description: 'New hashtags have been generated by the AI.',
      });
    } catch (error) {
      console.error('Error regenerating hashtags:', error);
      toast({
        variant: 'destructive',
        title: 'Hashtag Generation Failed',
        description: 'Could not generate new hashtags. Please try again.',
      });
    } finally {
      setIsGeneratingHashtags(false);
    }
  };


  if (!post) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Edit Post for {post.day}</DialogTitle>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="caption">Caption (EN)</Label>
            <Textarea
              id="caption"
              value={caption}
              onChange={(e) => setCaption(e.target.value)}
              rows={6}
            />
          </div>
          <div className="grid gap-2">
            <div className='flex justify-between items-center'>
                <Label htmlFor="hashtags">Hashtags (one per line)</Label>
                <Button variant="ghost" size="sm" onClick={handleRegenerateHashtags} disabled={isGeneratingHashtags}>
                    {isGeneratingHashtags ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Wand2 className="h-4 w-4 mr-2" />}
                    Regenerate
                </Button>
            </div>
            <Textarea
              id="hashtags"
              value={hashtags}
              onChange={(e) => setHashtags(e.target.value)}
              rows={4}
              disabled={isGeneratingHashtags}
            />
          </div>
        </div>
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="secondary">
              Cancel
            </Button>
          </DialogClose>
          <Button type="button" onClick={handleSave}>
            Save Changes
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
